import test from 'node:test';import assert from 'node:assert/strict';
import {normalize} from './catalog.mjs';import {validate,loadRegistry} from './runtime.mjs';
import {deviceValue,validateVariables,validateAction,validateGraph,validateExpression} from './semantics.mjs';
import {loadEnvelopes,validateEnvelope,planMapping} from './transport.mjs';
const id='test/schema.json';function reg(raw,profile='form'){const issues=[];return {resources:{[id]:{schema:normalize(raw,'',issues,profile),issues}}};}
test('device slots use ordered values and preserve array-valued slots',()=>{assert.deepEqual(deviceValue(false),[null,false]);let r=reg({valueType:'number',allowDevice:true});assert.ok(validate(r,id,[null,12]).valid);assert.equal(validate(r,id,[null,'12']).valid,false);assert.equal(validate(r,id,{'1':12}).valid,false);r=reg({valueType:'array',allowDevice:true});assert.ok(validate(r,id,[null,{top:'--sp--s0'}]).valid);});
test('requiredForBuild applies without making key attributes required',()=>{const r=reg({configurations:{title:{valueType:'string',requiredForBuild:true},optional:{valueType:'string',isKeyAttribute:true}}});assert.equal(validate(r,id,{}).valid,false);assert.ok(validate(r,id,{title:'x'}).valid);});
test('dynamic type depends on authoritative sibling selector',()=>{const r=reg({properties:{type:{type:'string'},value:{valueType:'string',valueTypeBy:{property:'type','0':'string','1':'object','2':'array'},isFormula:true}}});assert.ok(validate(r,id,{type:'0',value:'text'}).valid);assert.equal(validate(r,id,{type:'1',value:'text'}).valid,false);assert.equal(validate(r,id,{type:'9',value:'text'}).status,'blocked');assert.equal(validate(r,id,{type:'2',value:[{type:'text',value:'x'}]}).status,'blocked');});
test('action numeric enums are scoped and not coerced globally',()=>{const schema={valueType:'enum',enum:{'3':'Label'}};assert.ok(validate(reg(schema,'action'),id,3).valid);assert.ok(validate(reg(schema,'action'),id,'3').valid);assert.equal(validate(reg(schema,'node'),id,3).valid,false);});
test('single formula variables and code require context/review',()=>{assert.equal(validate(reg({valueType:'object',isFormulaVars:true}),id,{id:'a'}).status,'blocked');assert.equal(validate(reg({valueType:'string',isCode:true}),id,'code').status,'blocked');});
test('variable categories are independent and list references close',()=>{const r=loadRegistry();const v={basic:[{id:'same',name:'Items',type:'list',value:'same'}],listref:[{id:'same',name:'Rows',fields:[{id:'same',name:'Text',type:'text'}]}],filter:[{id:'same'}],tempVars:[{id:'same'}]};assert.ok(validateVariables(r,v).valid);const bad=structuredClone(v);bad.basic[0].value='missing';assert.ok(validateVariables(r,bad).errors.some(x=>x.code==='LIST_REFERENCE_MISSING'));const dup=structuredClone(v);dup.basic.push({...dup.basic[0]});assert.ok(validateVariables(r,dup).errors.some(x=>x.code==='DUPLICATE_ID'));});
test('action dispatch rejects unknown types, unexpected attrs and category mismatches',()=>{const r=loadRegistry();const base={id:'c0ca39af-35b8-4ee2-bb30-091ebd520000',name:'Test',steps:[{type:'setvar'}]};assert.ok(validateAction(r,base).valid);assert.ok(validateAction(r,{...base,steps:[{type:'not-a-real-step'}]}).errors.some(x=>x.code==='UNKNOWN_STEP_TYPE'));assert.equal(validateAction(r,{...base,steps:[{type:'setvar',attrs:{invented:1}}]}).valid,false);const typed=Object.entries(r.resources).find(([id,x])=>id.startsWith('workflow/step/')&&x.actionCategories.length);assert.ok(typed);assert.ok(validateAction(r,{...base,steps:[{type:typed[1].controlTypes[0]}]}).errors.some(x=>x.code==='STEP_CATEGORY_MISMATCH'));});
test('graph verifies reciprocal edges and immutable resource identity',()=>{const r=loadRegistry();const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',f='00000000-0000-0000-0000-000000000003';const ref=id=>({id,resourceid:id});const nodes=[{...ref(a),stencil:{id:'StartNoneEvent'},properties:{},outgoing:[ref(f)],incoming:[]},{...ref(b),stencil:{id:'EndNoneEvent'},properties:{},incoming:[ref(f)],outgoing:[]},{...ref(f),stencil:{id:'SequenceFlow'},properties:{},source:ref(a),target:ref(b)}];assert.ok(validateGraph(r,nodes).valid);const broken=structuredClone(nodes);broken[1].incoming=[];assert.ok(validateGraph(r,broken).errors.some(x=>x.code==='FLOW_TARGET_OR_INCOMING_MISSING'));nodes[0].resourceid=b;assert.equal(validateGraph(r,nodes).valid,false);});
test('transport catches wrong casing, ID number and nested resource object',()=>{const r=loadEnvelopes();assert.equal(validateEnvelope(r,'ApprovalForm',{Name:'Test',ProcModelID:'123',Deployed:false}).valid,true);assert.equal(validateEnvelope(r,'ApprovalForm',{key:'x'}).valid,false);assert.equal(validateEnvelope(r,'ApprovalForm',{ProcModelID:123}).valid,false);assert.equal(validateEnvelope(r,'ApprovalForm',{DefResource:{nodes:[]}}).valid,false);assert.equal(validateEnvelope(r,'Dashboard',{LayoutInResources:[{Resource:{}}]}).valid,false);assert.equal(validateEnvelope(r,'DataList',{Fields:[]}).valid,false);assert.equal(planMapping('ApprovalForm').saveReady,false);});

test('workflow expression direct references require scope and authoritative variable IDs',()=>{const r=loadRegistry(),s=[{type:'variable',param:{id:'amount'},label:'Amount'}],variables={basic:[{id:'amount',name:'Amount',type:'number'}]};assert.ok(validateExpression(r,s,{scope:'workflow',variables}).valid);assert.equal(validateExpression(r,s,{scope:'list.notification',variables}).valid,false);assert.equal(validateExpression(r,s,{scope:'workflow',variables:{basic:[]}}).valid,false);assert.equal(validateExpression(r,s,{scope:'workflow'}).status,'blocked');assert.ok(validateExpression(r,[{type:'text',value:'test'}],{scope:'workflow'}).valid);});
test('required build properties cannot disappear with their parent',()=>{const r=reg({configurations:{attrs:{properties:{title:{valueType:'string',requiredForBuild:true}}}}});assert.equal(validate(r,id,{}).valid,false);assert.ok(validate(r,id,{attrs:{title:'x'}}).valid);});
